trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage1
    jobs:
      - job: job1
        steps:
          - task: CmdLine@2
            inputs:
              script: 'echo Hi Harsha'
            displayName: Task1
          - task: CmdLine@2
            inputs:
              script: 'echo Hi Sai'
            displayName: Task2
      - job: job2
        steps:
          - task: CmdLine@2
            inputs:
              script: 'echo Hi Hemanth'
            displayName: Task3
  - stage: stage2
    jobs:
      - job: job3
        steps:
          - task: CmdLine@2
            inputs:
              script: 'echo Hi Giri'
            displayName: Task4