name: Angular CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: NPM Install
      run: npm Install
      working-directory: .
      
    - name: NPM Build
      run: npm run build
      working-directory: .

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: dist/angular-conduit


    
